import SwiftUI

// Operator-only diagnostic: does this Apple TV actually open each streaming
// app? Reached from the Account tab, admin sessions only.
//
// Why it exists: streaming services quietly retire their URL schemes, and the
// only way to find out is to try one on a real device. Before this screen the
// loop was "notice a dead Watch button on some show, guess which leg failed,
// ship a build to find out." Here every candidate is one press, and the result
// is recorded.
//
// Why openURL and not canOpenURL: canOpenURL would report which schemes are
// registered without leaving the app, but it only answers for schemes declared
// in LSApplicationQueriesSchemes, and this target's Info.plist is generated by
// Xcode (GENERATE_INFOPLIST_FILE) so it can't carry that array. openURL needs
// no declaration, and its completion reports acceptance — plus, on success you
// land in the app, which is the thing being tested.
//
// A pass therefore switches apps. Results are written to UserDefaults the
// moment the completion fires, so they survive the trip and are still on
// screen when you come back.
struct StreamingLinkCheckView: View {
    @Environment(\.openURL) private var openURL
    @Environment(\.dismiss) private var dismiss
    @State private var results: [String: Bool] = StreamingLinkCheckView.loadResults()

    var body: some View {
        ZStack {
            Theme.background.ignoresSafeArea()
            ScrollView {
                VStack(alignment: .leading, spacing: 34) {
                    header
                    ForEach(StreamingApps.all) { service in
                        serviceRow(service)
                    }
                    directLinkNote
                    Button("Clear results") { clearResults() }
                        .buttonStyle(ChipButtonStyle())
                        .padding(.top, 12)
                }
                .padding(60)
            }
        }
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Streaming Link Check")
                .font(.system(size: 48, weight: .bold))
                .foregroundColor(Theme.text)
            Text("Press a scheme to try opening that app on this Apple TV. If it opens, the app switches away — come back and the result will be recorded here.")
                .font(.system(size: 24))
                .foregroundColor(Theme.muted)
                .frame(maxWidth: 1100, alignment: .leading)
        }
    }

    @ViewBuilder private func serviceRow(_ service: StreamingApps.Service) -> some View {
        VStack(alignment: .leading, spacing: 14) {
            HStack(spacing: 16) {
                Text(service.name)
                    .font(.system(size: 32, weight: .semibold))
                    .foregroundColor(Theme.text)
                if let note = service.lastKnown {
                    Text(note)
                        .font(.system(size: 20))
                        .foregroundColor(Theme.muted)
                }
            }
            HStack(spacing: 16) {
                ForEach(service.schemes, id: \.self) { scheme in
                    Button { probe(scheme) } label: {
                        HStack(spacing: 10) {
                            statusDot(for: scheme)
                            Text("\(scheme)://")
                        }
                        .font(.system(size: 24, weight: .semibold))
                        .lineLimit(1)
                        .fixedSize()
                    }
                    .buttonStyle(ChipButtonStyle())
                }
            }
        }
    }

    // Green when this device opened it, red when it refused, hollow when the
    // scheme hasn't been pressed yet. Shape as well as color, so the state
    // survives a TV with the color turned down.
    @ViewBuilder private func statusDot(for scheme: String) -> some View {
        switch results[scheme] {
        case .some(true):
            Image(systemName: "checkmark.circle.fill").foregroundColor(.green)
        case .some(false):
            Image(systemName: "xmark.circle.fill").foregroundColor(.red)
        case nil:
            Image(systemName: "circle").foregroundColor(Theme.muted)
        }
    }

    private var directLinkNote: some View {
        Text("HBO Max and Apple TV+ aren't listed: their tvOS apps handle their own https URLs and land on the actual show, so they need no scheme. Everything above can only open its app to the home screen — tvOS gives third-party apps no way to reach another app except a registered URL scheme.")
            .font(.system(size: 20))
            .foregroundColor(Theme.muted)
            .frame(maxWidth: 1100, alignment: .leading)
            .padding(.top, 18)
    }

    private func probe(_ scheme: String) {
        guard let url = URL(string: "\(scheme)://") else { return }
        openURL(url) { accepted in
            record(scheme, accepted)
        }
    }

    // MARK: Persistence
    //
    // A successful open backgrounds this app, so the result has to be durable
    // before the switch rather than held in view state.

    private static let storeKey = "streamingLinkCheck.results"

    private static func loadResults() -> [String: Bool] {
        (UserDefaults.standard.dictionary(forKey: storeKey) as? [String: Bool]) ?? [:]
    }

    private func record(_ scheme: String, _ accepted: Bool) {
        results[scheme] = accepted
        UserDefaults.standard.set(results, forKey: Self.storeKey)
    }

    private func clearResults() {
        results = [:]
        UserDefaults.standard.removeObject(forKey: Self.storeKey)
    }
}
