import SwiftUI

// Operator-only diagnostic: does this Apple TV actually open each streaming
// app? Reached from the Account tab, admin sessions only.
//
// Why it exists: streaming services quietly retire their URL schemes, and the
// only way to find out is to try one on a real device. Before this screen the
// loop was "notice a dead Watch button on some show, guess which leg failed,
// ship a build to find out." Here every candidate is one press, and the result
// is recorded.
//
// Why openURL and not canOpenURL: canOpenURL would report which schemes are
// registered without leaving the app, but it only answers for schemes declared
// in LSApplicationQueriesSchemes, and this target's Info.plist is generated by
// Xcode (GENERATE_INFOPLIST_FILE) so it can't carry that array. openURL needs
// no declaration, and its completion reports acceptance — plus, on success you
// land in the app, which is the thing being tested.
//
// A pass therefore switches apps. Results are written to UserDefaults the
// moment the completion fires, so they survive the trip and are still on
// screen when you come back.
struct StreamingLinkCheckView: View {
    @Environment(\.openURL) private var openURL
    @Environment(\.dismiss) private var dismiss
    @State private var results: [String: Bool] = StreamingLinkCheckView.loadResults()

    var body: some View {
        ZStack {
            Theme.background.ignoresSafeArea()
            ScrollView {
                VStack(alignment: .leading, spacing: 34) {
                    header
                    sectionHeading("Does the app open?",
                                   detail: "A bare scheme, so a pass lands on the app's own home screen.")
                    ForEach(StreamingApps.all) { service in
                        serviceRow(service)
                    }
                    sectionHeading("Does it open on the show?",
                                   detail: "A real title with the real link the club stored for it. Apple TV+ and HBO Max are the controls; the rest are unproven, and a red row is a result, not a bug.\n\nRead the dot narrowly: green means the device ACCEPTED the URL, not that it landed on the show. Prime Video accepts a link and then says it can't stream the title. Only what you see on screen after the switch answers the question in the heading.")
                    ForEach(StreamingApps.showLinks) { link in
                        showLinkRow(link)
                    }
                    directLinkNote
                    Button("Clear results") { clearResults() }
                        .buttonStyle(ChipButtonStyle())
                        .padding(.top, 12)
                }
                .padding(60)
            }
        }
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Streaming Link Check")
                .font(.system(size: 48, weight: .bold))
                .foregroundColor(Theme.text)
            Text("Press a scheme to try opening that app on this Apple TV. If it opens, the app switches away — come back and the result will be recorded here.")
                .font(.system(size: 24))
                .foregroundColor(Theme.muted)
                .frame(maxWidth: 1100, alignment: .leading)
        }
    }

    @ViewBuilder private func serviceRow(_ service: StreamingApps.Service) -> some View {
        VStack(alignment: .leading, spacing: 14) {
            HStack(spacing: 16) {
                Text(service.name)
                    .font(.system(size: 32, weight: .semibold))
                    .foregroundColor(Theme.text)
                if let note = service.lastKnown {
                    Text(note)
                        .font(.system(size: 20))
                        .foregroundColor(Theme.muted)
                }
            }
            HStack(spacing: 16) {
                ForEach(service.schemes, id: \.self) { scheme in
                    Button { probe(scheme) } label: {
                        HStack(spacing: 10) {
                            statusDot(for: scheme)
                            Text("\(scheme)://")
                        }
                        .font(.system(size: 24, weight: .semibold))
                        .lineLimit(1)
                        .fixedSize()
                    }
                    .buttonStyle(ChipButtonStyle())
                }
            }
        }
    }

    private func sectionHeading(_ title: String, detail: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.system(size: 34, weight: .bold))
                .foregroundColor(Theme.text)
            Text(detail)
                .font(.system(size: 20))
                .foregroundColor(Theme.muted)
                .frame(maxWidth: 1100, alignment: .leading)
        }
        .padding(.top, 20)
    }

    // Same shape as serviceRow, but each button is a full URL rather than a
    // bare scheme, and the row names the title being used so a stale sample is
    // recognisable as a stale sample.
    @ViewBuilder private func showLinkRow(_ link: StreamingApps.ShowLink) -> some View {
        VStack(alignment: .leading, spacing: 14) {
            HStack(spacing: 16) {
                Text("\(link.service) · \(link.title)")
                    .font(.system(size: 32, weight: .semibold))
                    .foregroundColor(Theme.text)
                if let note = link.note {
                    Text(note)
                        .font(.system(size: 20))
                        .foregroundColor(Theme.muted)
                }
            }
            HStack(spacing: 16) {
                ForEach(link.candidates) { candidate in
                    Button { probe(url: candidate.url) } label: {
                        HStack(spacing: 10) {
                            statusDot(for: candidate.url)
                            Text(candidate.label)
                        }
                        .font(.system(size: 24, weight: .semibold))
                        .lineLimit(1)
                        .fixedSize()
                    }
                    .buttonStyle(ChipButtonStyle())
                }
            }
            // The exact string that was sent, so a result can be reproduced
            // (or corrected) without reading the source.
            ForEach(link.candidates) { candidate in
                Text(candidate.url)
                    .font(.system(size: 16))
                    .foregroundColor(Theme.muted)
                    .lineLimit(1)
                    .truncationMode(.middle)
                    .frame(maxWidth: 1100, alignment: .leading)
            }
        }
    }

    // Green when this device opened it, red when it refused, hollow when the
    // scheme hasn't been pressed yet. Shape as well as color, so the state
    // survives a TV with the color turned down.
    @ViewBuilder private func statusDot(for key: String) -> some View {
        switch results[key] {
        case .some(true):
            Image(systemName: "checkmark.circle.fill").foregroundColor(.green)
        case .some(false):
            Image(systemName: "xmark.circle.fill").foregroundColor(.red)
        case nil:
            Image(systemName: "circle").foregroundColor(Theme.muted)
        }
    }

    private var directLinkNote: some View {
        Text("HBO Max and Apple TV+ have no scheme row: their tvOS apps handle their own https URLs, so the show link above is the whole story for them. Everywhere else tvOS gives third-party apps no way to reach another app except a registered URL scheme, which is why a service can open its app and still not reach the show.")
            .font(.system(size: 20))
            .foregroundColor(Theme.muted)
            .frame(maxWidth: 1100, alignment: .leading)
            .padding(.top, 18)
    }

    private func probe(_ scheme: String) {
        probe(url: "\(scheme)://")
    }

    // Results are keyed by the exact string sent, so a scheme row and a show
    // row never collide even when they open the same app.
    private func probe(url string: String) {
        guard let url = URL(string: string) else { return }
        openURL(url) { accepted in
            record(string, accepted)
        }
    }

    // MARK: Persistence
    //
    // A successful open backgrounds this app, so the result has to be durable
    // before the switch rather than held in view state.

    private static let storeKey = "streamingLinkCheck.results"

    private static func loadResults() -> [String: Bool] {
        (UserDefaults.standard.dictionary(forKey: storeKey) as? [String: Bool]) ?? [:]
    }

    private func record(_ key: String, _ accepted: Bool) {
        results[key] = accepted
        UserDefaults.standard.set(results, forKey: Self.storeKey)
    }

    private func clearResults() {
        results = [:]
        UserDefaults.standard.removeObject(forKey: Self.storeKey)
    }
}
