-- One-time correction to a single member's display name and login email.
--
-- Applied to production in 2026-07. The statements named real members and have
-- been removed now that this repository is public. Migrations are tracked by
-- filename (scripts/apply-migrations.sh), so this file is never re-run, and a
-- fresh database is built from schema.sql, not from this set.
