-- Where a title streams *now*, according to TMDB, alongside the network the
-- member recorded — never instead of it.
--
-- `shows.network` is written fill-only (`network = COALESCE(network, ?)`) in
-- both enrichment passes, so once it is set — by the member's pick or by
-- TMDB when they left it blank — it is never revisited. Licensing moves and
-- the record doesn't: 61 of 137 unarchived films (45%) carry a network TMDB
-- no longer lists as a US flatrate provider. Conclave says Apple TV+ while
-- TMDB says Starz; Avatar says Netflix while TMDB says Paramount+.
--
-- Overwriting `network` from TMDB would silently discard a deliberate member
-- answer, which is the whole reason that write is fill-only — and we store no
-- provenance that could tell a member's pick from a machine's. So this column
-- carries TMDB's current answer beside it and the UI surfaces the difference.
-- Unlike `network`, it is pure derived data with no member intent in it, so
-- enrichment refreshes it authoritatively on every pass.
--
-- Comma-separated canonical network names, matching `network`'s vocabulary
-- (`_shared/networks.js`) — only providers that map to a service we can name,
-- so a reseller listing like "Starz Amazon Channel" is omitted rather than
-- shown as a service nobody subscribes to under that name. NULL means TMDB
-- was never asked; empty string means it was asked and named nothing.
ALTER TABLE shows ADD COLUMN streaming_on TEXT;
