#!/usr/bin/env python3
"""Post the invariants-review findings as a PR comment.

    scripts/post-pr-comment.py <owner/repo> <pr-number> <findings-file>

Needs GH_TOKEN. Exits 0 when there's nothing to say.
"""

import json
import os
import sys
import urllib.error
import urllib.request

FOOTER = (
    "\nThis is advisory and does not block the merge — `PR checks` is the gate. "
    "If a finding is wrong, the rule it cites probably needs rewording in "
    "`docs/INVARIANTS.md`.\n\n"
    "---\n_Generated by [Claude Code](https://claude.ai/code)_\n"
)


def main() -> int:
    repo, pr, path = sys.argv[1], sys.argv[2], sys.argv[3]

    findings = open(path).read().strip()
    if not findings:
        print("No findings to post.")
        return 0

    token = os.environ.get("GH_TOKEN")
    if not token:
        print("GH_TOKEN not set — printing findings instead of posting.\n")
        print(findings)
        return 0

    body = (
        "**Invariants review** — checked against `docs/INVARIANTS.md`.\n\n"
        + findings
        + "\n"
        + FOOTER
    )

    req = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/issues/{pr}/comments",
        data=json.dumps({"body": body}).encode(),
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as response:
            print("posted comment", json.load(response).get("id"))
    except urllib.error.URLError as exc:
        # Failing to comment shouldn't fail the build; the findings are in the
        # job log either way.
        print(f"Could not post the comment: {exc}\n")
        print(findings)
    return 0


if __name__ == "__main__":
    sys.exit(main())
